- name: Install mysql-server
  apt: pkg=default-mysql-server state=present
  register: sql_install_result

- name: Install python-mysqldb (required for ansible mysql_* modules)
  apt: pkg=python-mysqldb state=present
  when: ansible_python.version.major == 2

- name: Install python-pymsql (required for ansible mysql_* modules)
  apt: pkg=python3-pymysql state=present
  when: ansible_python.version.major == 3

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mariadb_root_password is defined
  register: mariadb_password_changed

- name: Change default sql authentication plugin for root user from unix_socket to normal password auth
  shell: >
    mysql -u root "-p{{ mariadb_root_password }}" -D mysql -NBe
    'UPDATE user SET plugin="" WHERE User="root" AND plugin = "unix_socket" OR plugin = "auth_socket";'
  when: mariadb_password_changed is changed
        and not (ansible_distribution == "Debian" and ansible_distribution_major_version|int > 10) # https://stackoverflow.com/questions/64841185/error-1356-hy000-view-mysql-user-references-invalid-tables-or-columns-o
  # default plugin is mysql_native_password on debian 11 anyway
  notify: Flush privileges

- name: copy .my.cnf file with root password credentials
  template: src="my.cnf.j2" dest="/root/.my.cnf" owner=root group=root mode=0600
  when: mariadb_root_password is defined

- name: Fix /etc/mysql/debian.cnf which is used by /etc/logrotate.d/mysql-server and /etc/mysql/debian-start (run during debian startup)
  ini_file:
    path: /etc/mysql/debian.cnf
    section: "{{ item }}"
    option: password
    value: "{{ mariadb_root_password }}"
  loop:
    - client
    - mysql_upgrade
  when: mariadb_root_password is defined

- name: Use innodb barracuda file format by default
  copy:
    src: use-barracuda.cnf
    dest: /etc/mysql/conf.d/
  notify: Restart mariadb
